# hugo.toml
baseURL = "https://dschchool.github.io/doan-hugo/"
languageCode = "vi" # Đổi sang Tiếng Việt
title = "DVT Blog"
theme = "hugo-PaperMod"

# ===============================================
# CẤU HÌNH GIAO DIỆN CHÍNH (THAY THẾ PHẦN [params] CŨ)
# ===============================================

[params]
  env = "production"
  defaultTheme = "light"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButton = false
  ShowSearch = true # Bật nút tìm kiếm

  # ===============================================
  # TÙY CHỈNH TRANG CHỦ (TẠO BANNER LỚN)
  # ===============================================
  [params.homeInfoParams]
    Title = "CHÀO MỪNG ĐẾN VỚI DVT BLOG" # Dùng chữ IN HOA để nổi bật
    Content = "Hành trình cooking môn lập trình mạng tính của một cậu SV."
    
  [params.socialIcons]
    # Bạn có thể thêm link GitHub, Facebook, etc. tại đây.
    
  # Cấu hình Footer
  [params.footer]
    showEdit = false
    showView = false
    showDate = false

# Cấu hình Menu (Đảm bảo đường dẫn /profile/ và /posts/ là chính xác)
[menu]
  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Bài Viết"
    url = "/posts/"
    weight = 20

# Cấu hình hiển thị code (Quan trọng cho bài viết kỹ thuật)
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = false
  tabWidth = 4

  # KÍCH HOẠT CUSTOM CSS:
  customCss = ["css/custom.css"]