# hugo.toml - Full Code Đã Sửa Lỗi Cú Pháp
baseURL = "https://dschchool.github.io/doan-hugo/"
languageCode = "vi"
title = "DVT Blog"
theme = "hugo-PaperMod"

# ===============================================
# CẤU HÌNH GIAO DIỆN CHÍNH (PARAMS)
# ===============================================

[params]
  env = "production"
  defaultTheme = "light"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButton = false
  ShowSearch = true # Bật nút tìm kiếm

  # KÍCH HOẠT CUSTOM CSS: LỆNH NÀY ĐÃ ĐƯỢC ĐẶT TRONG KHỐI [params]
  customCSS = ["css/custom.css"]

  # ===============================================
  # TÙY CHỈNH TRANG CHỦ (TẠO BANNER LỚN)
  # ===============================================
  [params.homeInfoParams]
    Title = "CHÀO MỪNG ĐẾN VỚI DVT BLOG" 
    Content = "Hành trình cooking món lập trình mạng tinh túy của một cậu SV."
    
  [params.socialIcons]
    # Thêm link GitHub, Facebook, etc. tại đây.
    
  # Cấu hình Footer
  [params.footer]
    showEdit = false
    showView = false
    showDate = false

# ===============================================
# Cấu hình Menu
# ===============================================
[menu]
  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Bài Viết"
    url = "/posts/"
    weight = 20

# ===============================================
# Cấu hình hiển thị code
# ===============================================
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = false
  tabWidth = 4